language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

git:
  submodules: false

warnings_are_errors: true
env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE

after_success:
  - Rscript -e 'covr::codecov()'
